from fief.schemas import (
    admin_api_key,
    auth,
    client,
    generics,
    oauth_provider,
    permission,
    role,
    tenant,
    user,
    user_field,
    user_permission,
    user_role,
    well_known,
    workspace,
)

__all__ = [
    "workspace",
    "admin_api_key",
    "auth",
    "client",
    "generics",
    "oauth_provider",
    "permission",
    "role",
    "tenant",
    "user",
    "user_field",
    "user_permission",
    "user_role",
    "well_known",
]
