"""Add models for social OAuth

Revision ID: 016036c553fa
Revises: 2b8bf1c3378e
Create Date: 2022-09-03 12:01:42.863070

"""
from alembic import op
import sqlalchemy as sa


import fief

# revision identifiers, used by Alembic.
revision = "016036c553fa"
down_revision = "2b8bf1c3378e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fief_oauth_providers",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column(
            "created_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.Text(), nullable=False),
        sa.Column("client_secret", sa.Text(), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("openid_configuration_endpoint", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fief_oauth_providers_created_at"),
        "fief_oauth_providers",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_oauth_providers_updated_at"),
        "fief_oauth_providers",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "fief_oauth_accounts",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column(
            "created_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column(
            "expires_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            nullable=True,
        ),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("account_id", sa.String(length=1024), nullable=False),
        sa.Column("account_email", sa.String(length=1024), nullable=True),
        sa.Column("oauth_provider_id", fief.models.generics.GUID(), nullable=False),
        sa.Column("user_id", fief.models.generics.GUID(), nullable=True),
        sa.Column("tenant_id", fief.models.generics.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["oauth_provider_id"], ["fief_oauth_providers.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["fief_tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["fief_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("oauth_provider_id", "user_id"),
    )
    op.create_index(
        op.f("ix_fief_oauth_accounts_account_id"),
        "fief_oauth_accounts",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_oauth_accounts_created_at"),
        "fief_oauth_accounts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_oauth_accounts_updated_at"),
        "fief_oauth_accounts",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "fief_oauth_sessions",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column(
            "created_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("redirect_uri", sa.Text(), nullable=False),
        sa.Column("oauth_provider_id", fief.models.generics.GUID(), nullable=False),
        sa.Column("login_session_id", fief.models.generics.GUID(), nullable=False),
        sa.Column("oauth_account_id", fief.models.generics.GUID(), nullable=True),
        sa.Column(
            "expires_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["login_session_id"], ["fief_login_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["oauth_account_id"], ["fief_oauth_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["oauth_provider_id"], ["fief_oauth_providers.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fief_oauth_sessions_created_at"),
        "fief_oauth_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_oauth_sessions_expires_at"),
        "fief_oauth_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_oauth_sessions_token"),
        "fief_oauth_sessions",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_fief_oauth_sessions_updated_at"),
        "fief_oauth_sessions",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "fief_registration_sessions",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column(
            "created_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("show_password", sa.Boolean(), nullable=False),
        sa.Column("oauth_account_id", fief.models.generics.GUID(), nullable=True),
        sa.Column("tenant_id", fief.models.generics.GUID(), nullable=False),
        sa.Column(
            "expires_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["oauth_account_id"], ["fief_oauth_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["fief_tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fief_registration_sessions_created_at"),
        "fief_registration_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_registration_sessions_expires_at"),
        "fief_registration_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_registration_sessions_token"),
        "fief_registration_sessions",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_fief_registration_sessions_updated_at"),
        "fief_registration_sessions",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fief_registration_sessions_updated_at"),
        table_name="fief_registration_sessions",
    )
    op.drop_index(
        op.f("ix_fief_registration_sessions_token"),
        table_name="fief_registration_sessions",
    )
    op.drop_index(
        op.f("ix_fief_registration_sessions_expires_at"),
        table_name="fief_registration_sessions",
    )
    op.drop_index(
        op.f("ix_fief_registration_sessions_created_at"),
        table_name="fief_registration_sessions",
    )
    op.drop_table("fief_registration_sessions")
    op.drop_index(
        op.f("ix_fief_oauth_sessions_updated_at"), table_name="fief_oauth_sessions"
    )
    op.drop_index(
        op.f("ix_fief_oauth_sessions_token"), table_name="fief_oauth_sessions"
    )
    op.drop_index(
        op.f("ix_fief_oauth_sessions_expires_at"), table_name="fief_oauth_sessions"
    )
    op.drop_index(
        op.f("ix_fief_oauth_sessions_created_at"), table_name="fief_oauth_sessions"
    )
    op.drop_table("fief_oauth_sessions")
    op.drop_index(
        op.f("ix_fief_oauth_accounts_updated_at"), table_name="fief_oauth_accounts"
    )
    op.drop_index(
        op.f("ix_fief_oauth_accounts_created_at"), table_name="fief_oauth_accounts"
    )
    op.drop_index(
        op.f("ix_fief_oauth_accounts_account_id"), table_name="fief_oauth_accounts"
    )
    op.drop_table("fief_oauth_accounts")
    op.drop_index(
        op.f("ix_fief_oauth_providers_updated_at"), table_name="fief_oauth_providers"
    )
    op.drop_index(
        op.f("ix_fief_oauth_providers_created_at"), table_name="fief_oauth_providers"
    )
    op.drop_table("fief_oauth_providers")
    # ### end Alembic commands ###
