"""Add RegisterSession model

Revision ID: 1b4889581d7c
Revises: 69af289ef2a7
Create Date: 2022-09-02 15:44:24.921224

"""
import sqlalchemy as sa
from alembic import op

import fief

# revision identifiers, used by Alembic.
revision = "1b4889581d7c"
down_revision = "69af289ef2a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fief_registration_sessions",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column(
            "created_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("user_id", fief.models.generics.GUID(), nullable=True),
        sa.Column("oauth_account_id", fief.models.generics.GUID(), nullable=True),
        sa.Column("tenant_id", fief.models.generics.GUID(), nullable=False),
        sa.Column(
            "expires_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["oauth_account_id"], ["fief_oauth_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["fief_tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["fief_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fief_registration_sessions_created_at"),
        "fief_registration_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_registration_sessions_expires_at"),
        "fief_registration_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_registration_sessions_token"),
        "fief_registration_sessions",
        ["token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_fief_registration_sessions_updated_at"),
        "fief_registration_sessions",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fief_registration_sessions_updated_at"),
        table_name="fief_registration_sessions",
    )
    op.drop_index(
        op.f("ix_fief_registration_sessions_token"),
        table_name="fief_registration_sessions",
    )
    op.drop_index(
        op.f("ix_fief_registration_sessions_expires_at"),
        table_name="fief_registration_sessions",
    )
    op.drop_index(
        op.f("ix_fief_registration_sessions_created_at"),
        table_name="fief_registration_sessions",
    )
    op.drop_table("fief_registration_sessions")
    # ### end Alembic commands ###
