"""Tweak RegisterSession model

Revision ID: 20bcd2a58633
Revises: 1b4889581d7c
Create Date: 2022-09-02 18:55:17.455697

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import fief

# revision identifiers, used by Alembic.
revision = "20bcd2a58633"
down_revision = "1b4889581d7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fief_registration_sessions",
        sa.Column("show_password", sa.Boolean(), nullable=False),
    )
    op.drop_constraint(
        "fief_registration_sessions_user_id_fkey",
        "fief_registration_sessions",
        type_="foreignkey",
    )
    op.drop_column("fief_registration_sessions", "user_id")
    op.drop_column("fief_registration_sessions", "email")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fief_registration_sessions",
        sa.Column("email", sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    )
    op.add_column(
        "fief_registration_sessions",
        sa.Column("user_id", postgresql.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "fief_registration_sessions_user_id_fkey",
        "fief_registration_sessions",
        "fief_users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("fief_registration_sessions", "show_password")
    # ### end Alembic commands ###
