"""Remove custom OAuth2 and change to OpenID

Revision ID: 20f48a1bff87
Revises: cd5d4ad21d55
Create Date: 2022-09-01 11:01:42.769255

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import fief

# revision identifiers, used by Alembic.
revision = "20f48a1bff87"
down_revision = "cd5d4ad21d55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fief_oauth_providers",
        sa.Column("openid_configuration_endpoint", sa.Text(), nullable=True),
    )
    op.drop_column("fief_oauth_providers", "access_token_endpoint")
    op.drop_column("fief_oauth_providers", "revoke_token_endpoint")
    op.drop_column("fief_oauth_providers", "refresh_token_endpoint")
    op.drop_column("fief_oauth_providers", "authorize_endpoint")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fief_oauth_providers",
        sa.Column("authorize_endpoint", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "fief_oauth_providers",
        sa.Column(
            "refresh_token_endpoint", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "fief_oauth_providers",
        sa.Column(
            "revoke_token_endpoint", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "fief_oauth_providers",
        sa.Column(
            "access_token_endpoint", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("fief_oauth_providers", "openid_configuration_endpoint")
    # ### end Alembic commands ###
