"""Add code_challenge and code_challenge_method to LoginSession and AuthorizationCode

Revision ID: 4d0532b3bf16
Revises: 1df8009b83c5
Create Date: 2022-03-31 14:33:38.831711

"""
import sqlalchemy as sa
from alembic import op

import fief

# revision identifiers, used by Alembic.
revision = "4d0532b3bf16"
down_revision = "1df8009b83c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fief_authorization_codes",
        sa.Column("code_challenge", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "fief_authorization_codes",
        sa.Column("code_challenge_method", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "fief_login_sessions",
        sa.Column("code_challenge", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "fief_login_sessions",
        sa.Column("code_challenge_method", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fief_login_sessions", "code_challenge_method")
    op.drop_column("fief_login_sessions", "code_challenge")
    op.drop_column("fief_authorization_codes", "code_challenge_method")
    op.drop_column("fief_authorization_codes", "code_challenge")
    # ### end Alembic commands ###
