"""Add UserPermission model

Revision ID: 58072f347962
Revises: cbfdc8a6c65e
Create Date: 2022-05-30 08:53:42.870056

"""
import sqlalchemy as sa
from alembic import op

import fief

# revision identifiers, used by Alembic.
revision = "58072f347962"
down_revision = "cbfdc8a6c65e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fief_user_permissions",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column(
            "created_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", fief.models.generics.GUID(), nullable=False),
        sa.Column("permission_id", fief.models.generics.GUID(), nullable=False),
        sa.Column("from_role_id", fief.models.generics.GUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_role_id"], ["fief_roles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["fief_permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["fief_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "permission_id", "from_role_id"),
    )
    op.create_index(
        op.f("ix_fief_user_permissions_created_at"),
        "fief_user_permissions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_user_permissions_updated_at"),
        "fief_user_permissions",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fief_user_permissions_updated_at"), table_name="fief_user_permissions"
    )
    op.drop_index(
        op.f("ix_fief_user_permissions_created_at"), table_name="fief_user_permissions"
    )
    op.drop_table("fief_user_permissions")
    # ### end Alembic commands ###
