"""Add UserRole model

Revision ID: 5b1df52167d6
Revises: 58072f347962
Create Date: 2022-05-30 17:28:30.519736

"""
import sqlalchemy as sa
from alembic import op

import fief

# revision identifiers, used by Alembic.
revision = "5b1df52167d6"
down_revision = "58072f347962"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fief_user_roles",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column(
            "created_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", fief.models.generics.GUID(), nullable=False),
        sa.Column("role_id", fief.models.generics.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["fief_roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["fief_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id"),
    )
    op.create_index(
        op.f("ix_fief_user_roles_created_at"),
        "fief_user_roles",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_user_roles_updated_at"),
        "fief_user_roles",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fief_user_roles_updated_at"), table_name="fief_user_roles")
    op.drop_index(op.f("ix_fief_user_roles_created_at"), table_name="fief_user_roles")
    op.drop_table("fief_user_roles")
    # ### end Alembic commands ###
