"""Tweak models for OAuth2

Revision ID: 69af289ef2a7
Revises: 20f48a1bff87
Create Date: 2022-09-01 18:41:42.916292

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import fief

# revision identifiers, used by Alembic.
revision = "69af289ef2a7"
down_revision = "20f48a1bff87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fief_oauth_accounts",
        sa.Column("tenant_id", fief.models.generics.GUID(), nullable=False),
    )
    op.alter_column(
        "fief_oauth_accounts",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "fief_oauth_accounts",
        "account_email",
        existing_type=sa.VARCHAR(length=1024),
        nullable=True,
    )
    op.alter_column(
        "fief_oauth_accounts", "user_id", existing_type=postgresql.UUID(), nullable=True
    )
    op.create_foreign_key(
        None,
        "fief_oauth_accounts",
        "fief_tenants",
        ["tenant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "fief_oauth_sessions",
        sa.Column("oauth_account_id", fief.models.generics.GUID(), nullable=True),
    )
    op.alter_column(
        "fief_oauth_sessions",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.create_foreign_key(
        None,
        "fief_oauth_sessions",
        "fief_oauth_accounts",
        ["oauth_account_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "fief_oauth_sessions", type_="foreignkey")
    op.alter_column(
        "fief_oauth_sessions",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_column("fief_oauth_sessions", "oauth_account_id")
    op.drop_constraint(None, "fief_oauth_accounts", type_="foreignkey")
    op.alter_column(
        "fief_oauth_accounts",
        "user_id",
        existing_type=postgresql.UUID(),
        nullable=False,
    )
    op.alter_column(
        "fief_oauth_accounts",
        "account_email",
        existing_type=sa.VARCHAR(length=1024),
        nullable=False,
    )
    op.alter_column(
        "fief_oauth_accounts",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_column("fief_oauth_accounts", "tenant_id")
    # ### end Alembic commands ###
