"""Add c_hash to AuthorizationCode

Revision ID: 8fca070a47d3
Revises: dd694ef44d17
Create Date: 2022-04-01 17:41:29.561231

"""
import sqlalchemy as sa
from alembic import op

import fief

# revision identifiers, used by Alembic.
revision = "8fca070a47d3"
down_revision = "dd694ef44d17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fief_authorization_codes",
        sa.Column("c_hash", sa.String(length=255), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fief_authorization_codes", "c_hash")
    # ### end Alembic commands ###
