"""Add tenant_id column to OAuthSession to allow generic callback URL

Revision ID: 9386de298a52
Revises: f4ea7d875e5d
Create Date: 2022-09-07 15:34:56.275050

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import fief

# revision identifiers, used by Alembic.
revision = "9386de298a52"
down_revision = "f4ea7d875e5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fief_oauth_sessions",
        sa.Column("tenant_id", fief.models.generics.GUID(), nullable=False),
    )
    op.create_foreign_key(
        "fief_oauth_sessions_tenant_id_fkey",
        "fief_oauth_sessions",
        "fief_tenants",
        ["tenant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fief_oauth_sessions_tenant_id_fkey", "fief_oauth_sessions", type_="foreignkey"
    )
    op.drop_column("fief_oauth_sessions", "tenant_id")
    # ### end Alembic commands ###
