"""Add OAuthProvider model

Revision ID: b2b8a6110627
Revises: 2b8bf1c3378e
Create Date: 2022-07-12 09:45:35.957584

"""
import sqlalchemy as sa
from alembic import op

import fief

# revision identifiers, used by Alembic.
revision = "b2b8a6110627"
down_revision = "2b8bf1c3378e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fief_oauth_providers",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column(
            "created_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.Text(), nullable=False),
        sa.Column("client_secret", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("authorize_endpoint", sa.Text(), nullable=True),
        sa.Column("access_token_endpoint", sa.Text(), nullable=True),
        sa.Column("refresh_token_endpoint", sa.Text(), nullable=True),
        sa.Column("revoke_token_endpoint", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fief_oauth_providers_created_at"),
        "fief_oauth_providers",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_oauth_providers_updated_at"),
        "fief_oauth_providers",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fief_oauth_providers_updated_at"), table_name="fief_oauth_providers"
    )
    op.drop_index(
        op.f("ix_fief_oauth_providers_created_at"), table_name="fief_oauth_providers"
    )
    op.drop_table("fief_oauth_providers")
    # ### end Alembic commands ###
