"""Add Role and Permission models

Revision ID: cbfdc8a6c65e
Revises: ac76d4c912eb
Create Date: 2022-05-25 11:21:57.580568

"""
import sqlalchemy as sa
from alembic import op

import fief

# revision identifiers, used by Alembic.
revision = "cbfdc8a6c65e"
down_revision = "ac76d4c912eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fief_permissions",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column(
            "created_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("codename", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codename"),
    )
    op.create_index(
        op.f("ix_fief_permissions_created_at"),
        "fief_permissions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fief_permissions_updated_at"),
        "fief_permissions",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "fief_roles",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column(
            "created_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            fief.models.generics.TIMESTAMPAware(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("granted_by_default", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fief_roles_created_at"), "fief_roles", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_fief_roles_updated_at"), "fief_roles", ["updated_at"], unique=False
    )
    op.create_table(
        "roles_permissions",
        sa.Column("role_id", fief.models.generics.GUID(), nullable=False),
        sa.Column("permission_id", fief.models.generics.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"], ["fief_permissions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_id"], ["fief_roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles_permissions")
    op.drop_index(op.f("ix_fief_roles_updated_at"), table_name="fief_roles")
    op.drop_index(op.f("ix_fief_roles_created_at"), table_name="fief_roles")
    op.drop_table("fief_roles")
    op.drop_index(op.f("ix_fief_permissions_updated_at"), table_name="fief_permissions")
    op.drop_index(op.f("ix_fief_permissions_created_at"), table_name="fief_permissions")
    op.drop_table("fief_permissions")
    # ### end Alembic commands ###
