"""Add scopes to OAuthProvider

Revision ID: cd5d4ad21d55
Revises: 41edb7931903
Create Date: 2022-08-31 14:11:03.215129

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import fief

# revision identifiers, used by Alembic.
revision = "cd5d4ad21d55"
down_revision = "41edb7931903"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fief_oauth_providers",
        sa.Column("scopes", sa.JSON(), nullable=False, server_default="[]"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fief_oauth_providers", "scopes")
    # ### end Alembic commands ###
