"""Add response_mode to LoginSession

Revision ID: dd694ef44d17
Revises: 4d0532b3bf16
Create Date: 2022-04-01 15:52:23.682487

"""
import sqlalchemy as sa
from alembic import op

import fief

# revision identifiers, used by Alembic.
revision = "dd694ef44d17"
down_revision = "4d0532b3bf16"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fief_login_sessions",
        sa.Column("response_mode", sa.String(length=255), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fief_login_sessions", "response_mode")
    # ### end Alembic commands ###
