name: "Lint backend"
description: "Run the linters and type checkers"

runs:
  using: "composite"

  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      shell: bash
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Lint and typecheck
      shell: bash
      working-directory: backend
      run: |
        hatch run lint-check
