"""Add sign_jwk column on Account

Revision ID: 02665ba60a85
Revises: dd7a54cfd1f0
Create Date: 2022-01-14 08:51:11.892472

"""
import sqlalchemy as sa

import fief
from alembic import op

# revision identifiers, used by Alembic.
revision = "02665ba60a85"
down_revision = "dd7a54cfd1f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("sign_jwk", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "sign_jwk")
    # ### end Alembic commands ###
