"""Remove JWK keys from Account

Revision ID: 206f2ddff4e1
Revises: f279c1997666
Create Date: 2022-01-25 07:14:12.341771

"""
import sqlalchemy as sa

import fief
from alembic import op

# revision identifiers, used by Alembic.
revision = "206f2ddff4e1"
down_revision = "f279c1997666"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "encrypt_jwk")
    op.drop_column("accounts", "sign_jwk")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("sign_jwk", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "accounts",
        sa.Column("encrypt_jwk", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
