"""Add initial migration

Revision ID: 30dd92f38907
Revises: 
Create Date: 2022-01-05 16:38:45.870099

"""
import sqlalchemy as sa

import fief
from alembic import op

# revision identifiers, used by Alembic.
revision = "30dd92f38907"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("database_url", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounts")
    # ### end Alembic commands ###
