"""Add SessionToken table

Revision ID: 99a6e5d2c342
Revises: 206f2ddff4e1
Create Date: 2022-01-26 14:18:29.205126

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import fief
from alembic import op

# revision identifiers, used by Alembic.
revision = "99a6e5d2c342"
down_revision = "206f2ddff4e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_tokens",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("raw_tokens", sa.Text(), nullable=False),
        sa.Column("raw_userinfo", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_tokens")
    # ### end Alembic commands ###
