"""Add created_at/updated_at columns

Revision ID: b6065150e7da
Revises: 99a6e5d2c342
Create Date: 2022-01-31 18:10:04.473483

"""
import sqlalchemy as sa

import fief
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6065150e7da"
down_revision = "99a6e5d2c342"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "accounts",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_accounts_created_at"), "accounts", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_accounts_updated_at"), "accounts", ["updated_at"], unique=False
    )
    op.add_column(
        "session_tokens",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "session_tokens",
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_session_tokens_created_at"),
        "session_tokens",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_tokens_updated_at"),
        "session_tokens",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_tokens_updated_at"), table_name="session_tokens")
    op.drop_index(op.f("ix_session_tokens_created_at"), table_name="session_tokens")
    op.drop_column("session_tokens", "updated_at")
    op.drop_column("session_tokens", "created_at")
    op.drop_index(op.f("ix_accounts_updated_at"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_created_at"), table_name="accounts")
    op.drop_column("accounts", "updated_at")
    op.drop_column("accounts", "created_at")
    # ### end Alembic commands ###
