"""Add domain column to account

Revision ID: dd7a54cfd1f0
Revises: 30dd92f38907
Create Date: 2022-01-08 14:08:28.133607

"""
import sqlalchemy as sa

import fief
from alembic import op

# revision identifiers, used by Alembic.
revision = "dd7a54cfd1f0"
down_revision = "30dd92f38907"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("domain", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "domain")
    # ### end Alembic commands ###
