"""Make account database_url optional

Revision ID: f279c1997666
Revises: 02665ba60a85
Create Date: 2022-01-14 16:19:14.971351

"""
import sqlalchemy as sa

import fief
from alembic import op

# revision identifiers, used by Alembic.
revision = "f279c1997666"
down_revision = "02665ba60a85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("encrypt_jwk", sa.Text(), nullable=True))
    op.alter_column("accounts", "database_url", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("accounts", "database_url", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("accounts", "encrypt_jwk")
    # ### end Alembic commands ###
