"""Add AuthorizationCode table

Revision ID: 3ac554a12a09
Revises: e759937faf36
Create Date: 2022-01-09 16:36:03.081619

"""
import sqlalchemy as sa

import fief
from alembic import op

# revision identifiers, used by Alembic.
revision = "3ac554a12a09"
down_revision = "e759937faf36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fief_authorization_codes",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column("code", sa.String(length=255), nullable=False),
        sa.Column("redirect_uri", sa.String(length=2048), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=True),
        sa.Column("user_id", fief.models.generics.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["fief_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fief_authorization_codes_code"),
        "fief_authorization_codes",
        ["code"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fief_authorization_codes_code"), table_name="fief_authorization_codes"
    )
    op.drop_table("fief_authorization_codes")
    # ### end Alembic commands ###
