"""Add Tenant client_id and client_secret

Revision ID: 7e272ec80b8f
Revises: ba379c352a71
Create Date: 2022-01-07 18:06:17.671823

"""
import sqlalchemy as sa

import fief
from alembic import op

# revision identifiers, used by Alembic.
revision = "7e272ec80b8f"
down_revision = "ba379c352a71"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fief_tenants", sa.Column("client_id", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "fief_tenants",
        sa.Column("client_secret", sa.String(length=255), nullable=False),
    )
    op.create_index(
        op.f("ix_fief_tenants_client_id"), "fief_tenants", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_fief_tenants_client_secret"),
        "fief_tenants",
        ["client_secret"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fief_tenants_client_secret"), table_name="fief_tenants")
    op.drop_index(op.f("ix_fief_tenants_client_id"), table_name="fief_tenants")
    op.drop_column("fief_tenants", "client_secret")
    op.drop_column("fief_tenants", "client_id")
    # ### end Alembic commands ###
