"""Initial migration

Revision ID: c790f44ecd59
Revises:
Create Date: 2022-01-23 17:40:39.161363

"""
import sqlalchemy as sa

import fief
from alembic import op

# revision identifiers, used by Alembic.
revision = "c790f44ecd59"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fief_tenants",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("default", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "fief_clients",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("client_secret", sa.String(length=255), nullable=False),
        sa.Column("tenant_id", fief.models.generics.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["fief_tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fief_clients_client_id"), "fief_clients", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_fief_clients_client_secret"),
        "fief_clients",
        ["client_secret"],
        unique=False,
    )
    op.create_table(
        "fief_users",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=72), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", fief.models.generics.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["fief_tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", "tenant_id"),
    )
    op.create_index(op.f("ix_fief_users_email"), "fief_users", ["email"], unique=False)
    op.create_table(
        "fief_authorization_codes",
        sa.Column("id", fief.models.generics.GUID(), nullable=False),
        sa.Column("code", sa.String(length=255), nullable=False),
        sa.Column("redirect_uri", sa.String(length=2048), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=True),
        sa.Column("user_id", fief.models.generics.GUID(), nullable=False),
        sa.Column("client_id", fief.models.generics.GUID(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["fief_clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["fief_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fief_authorization_codes_code"),
        "fief_authorization_codes",
        ["code"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fief_authorization_codes_code"), table_name="fief_authorization_codes"
    )
    op.drop_table("fief_authorization_codes")
    op.drop_index(op.f("ix_fief_users_email"), table_name="fief_users")
    op.drop_table("fief_users")
    op.drop_index(op.f("ix_fief_clients_client_secret"), table_name="fief_clients")
    op.drop_index(op.f("ix_fief_clients_client_id"), table_name="fief_clients")
    op.drop_table("fief_clients")
    op.drop_table("fief_tenants")
    # ### end Alembic commands ###
