name: "Docker Build"
description: "Build and push Docker image"

inputs:
  fief_version:
    description: "Fief version"
    required: true
  tags:
    description: "Tags (following Docker metadata syntax)"
    required: true
  sep_tags:
    description: "Tags separator. Should be ' ' for manual Docker build"
    default: \n
  registry:
    description: "Docker registry"
    required: true
    default: ghcr.io
  image_name:
    description: "Docker image name"
    required: true
  github_token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: ${{ inputs.tags }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        build-args: |
          FIEF_VERSION=${{ inputs.fief_version }}
        context: docker/
        platforms: linux/amd64, linux/arm64
        push: true
        sep-tags: ${{ steps.meta.outputs.sep_tags }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    - name: Save cache
      uses: actions/cache/save@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
