name: "Lint"
description: "Run the linters and type checkers"

runs:
  using: "composite"

  steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Lint and typecheck
      shell: bash
      run: |
        hatch run lint-check
