"""Add application_url to Tenant

Revision ID: 095306ad19a5
Revises: ac62100e37c4
Create Date: 2023-03-28 13:29:27.867768

"""
import sqlalchemy as sa
from alembic import op

import fief

# revision identifiers, used by Alembic.
revision = "095306ad19a5"
down_revision = "ac62100e37c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fief_tenants",
        sa.Column("application_url", sa.String(length=512), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fief_tenants", "application_url")
    # ### end Alembic commands ###
